import asyncio
import json
import logging
import httpx
from typing import List, Dict, Any
from app.ai.providers.base import BaseAIProvider
from app.schemas.ai import LLMMessage, LLMResponse

logger = logging.getLogger(__name__)

_MAX_ATTEMPTS = 3
_RETRYABLE_STATUS = {429, 500, 502, 503, 504}
_THINKING_HEADROOM_TOKENS = 4096

class GeminiProvider(BaseAIProvider):
    def __init__(self, model_name: str = "gemini-3.8-flash", api_key: str = "", **kwargs):
        super().__init__(model_name=model_name, **kwargs)
        self.api_key = api_key

    async def generate(
        self,
        messages: List[LLMMessage],
        temperature: float = 0.5,
        max_tokens: int = 2048,
        **kwargs
    ) -> LLMResponse:
        if not self.api_key:
            return LLMResponse(
                content="[SIMULATION ENGINE - GEMINI KEY NOT CONFIGURED]: Operating in offline high-fidelity simulation mode.",
                provider="gemini_sim",
                model=self.model_name
            )

        endpoint = f"https://generativelanguage.googleapis.com/v1beta/models/{self.model_name}:generateContent"
        
        contents = []
        for m in messages:
            role = "user" if m.role in ["user", "system"] else "model"
            contents.append({
                "role": role,
                "parts": [{"text": m.content}]
            })

        payload = {
            "contents": contents,
            "generationConfig": {
                "temperature": temperature,
                # Gemini 3 thinking tokens count against this limit; reserve room so answers aren't cut off
                "maxOutputTokens": max_tokens + _THINKING_HEADROOM_TOKENS
            }
        }

        try:
            async with httpx.AsyncClient(timeout=45.0) as client:
                for attempt in range(_MAX_ATTEMPTS):
                    # Key goes in a header, not the URL, so it never lands in logs or tracebacks
                    res = await client.post(endpoint, json=payload, headers={"x-goog-api-key": self.api_key})
                    if res.status_code == 200:
                        data = res.json()
                        candidates = data.get("candidates", [])
                        if candidates:
                            parts = candidates[0].get("content", {}).get("parts", [])
                            text = "".join(p.get("text", "") for p in parts if not p.get("thought"))
                            return LLMResponse(content=text, provider="gemini", model=self.model_name)
                        break
                    logger.warning(f"Gemini API returned status {res.status_code} (attempt {attempt + 1}): {res.text[:300]}")
                    # Overload / rate limit is usually brief; anything else won't fix itself
                    if res.status_code not in _RETRYABLE_STATUS or attempt == _MAX_ATTEMPTS - 1:
                        break
                    await asyncio.sleep(2 ** attempt)
        except Exception as e:
            logger.warning(f"Gemini request failed: {e}")

        return LLMResponse(
            content="[SIMULATION ENGINE]: Response generated by offline fallback system.",
            provider="gemini_fallback",
            model=self.model_name
        )

    async def structured_generate(
        self,
        messages: List[LLMMessage],
        schema: Any,
        temperature: float = 0.2,
        **kwargs
    ) -> Any:
        sys_prompt = f"\nReturn strictly a JSON object conforming to this schema:\n{schema.model_json_schema()}"
        augmented = list(messages)
        augmented[-1] = LLMMessage(role=augmented[-1].role, content=augmented[-1].content + sys_prompt)
        res = await self.generate(augmented, temperature=temperature)
        try:
            clean = res.content.strip()
            if clean.startswith("```json"):
                clean = clean[7:]
            if clean.startswith("```"):
                clean = clean[3:]
            if clean.endswith("```"):
                clean = clean[:-3]
            return schema.model_validate_json(clean.strip())
        except Exception as e:
            logger.warning(f"Gemini structured generation parse error: {e}")
            return None
