import json
import logging
import httpx
from typing import List, Dict, Any
from app.ai.providers.base import BaseAIProvider
from app.schemas.ai import LLMMessage, LLMResponse

logger = logging.getLogger(__name__)

class GeminiProvider(BaseAIProvider):
    def __init__(self, model_name: str = "gemini-3.8-flash", api_key: str = "", **kwargs):
        super().__init__(model_name=model_name, **kwargs)
        self.api_key = api_key

    async def generate(
        self,
        messages: List[LLMMessage],
        temperature: float = 0.5,
        max_tokens: int = 2048,
        **kwargs
    ) -> LLMResponse:
        if not self.api_key:
            return LLMResponse(
                content="[SIMULATION ENGINE - GEMINI KEY NOT CONFIGURED]: Operating in offline high-fidelity simulation mode.",
                provider="gemini_sim",
                model=self.model_name
            )

        endpoint = f"https://generativelanguage.googleapis.com/v1beta/models/{self.model_name}:generateContent"
        
        contents = []
        for m in messages:
            role = "user" if m.role in ["user", "system"] else "model"
            contents.append({
                "role": role,
                "parts": [{"text": m.content}]
            })

        payload = {
            "contents": contents,
            "generationConfig": {
                "temperature": temperature,
                "maxOutputTokens": max_tokens
            }
        }

        try:
            async with httpx.AsyncClient(timeout=45.0) as client:
                # Key goes in a header, not the URL, so it never lands in logs or tracebacks
                res = await client.post(endpoint, json=payload, headers={"x-goog-api-key": self.api_key})
                if res.status_code == 200:
                    data = res.json()
                    candidates = data.get("candidates", [])
                    if candidates:
                        text = candidates[0].get("content", {}).get("parts", [{}])[0].get("text", "")
                        return LLMResponse(content=text, provider="gemini", model=self.model_name)
                logger.warning(f"Gemini API returned status {res.status_code}: {res.text}")
        except Exception as e:
            logger.warning(f"Gemini request failed: {e}")

        return LLMResponse(
            content="[SIMULATION ENGINE]: Response generated by offline fallback system.",
            provider="gemini_fallback",
            model=self.model_name
        )

    async def structured_generate(
        self,
        messages: List[LLMMessage],
        schema: Any,
        temperature: float = 0.2,
        **kwargs
    ) -> Any:
        sys_prompt = f"\nReturn strictly a JSON object conforming to this schema:\n{schema.model_json_schema()}"
        augmented = list(messages)
        augmented[-1] = LLMMessage(role=augmented[-1].role, content=augmented[-1].content + sys_prompt)
        res = await self.generate(augmented, temperature=temperature)
        try:
            clean = res.content.strip()
            if clean.startswith("```json"):
                clean = clean[7:]
            if clean.startswith("```"):
                clean = clean[3:]
            if clean.endswith("```"):
                clean = clean[:-3]
            return schema.model_validate_json(clean.strip())
        except Exception as e:
            logger.warning(f"Gemini structured generation parse error: {e}")
            return None
